### PR TITLE
Pdf generation branch

### PR DESCRIPTION
**Pull request by ValgardurRI**
Launching the code to heroku works, so it's safe to push to master

### CODE REVIEW

**Review by ribombee — APPROVED** [review]
Looks good

**Comment by emil-snorri** [comment]
One of the travis build checks seems to be frozen
Edit: it's fixed

**Review by emil-snorri — APPROVED** [review]
I approve

**Comment by ValgardurRI** [comment]
Restarting the build seems to have fixed it

**Pull request merged**
